language: groovy

jdk:
  - oraclejdk8

env:
  - GRAILS_VERSION=2.4.2

before_install:
- rm -rf ~/.sdkman
- curl -s http://get.sdkman.io > ~/install_sdk.sh
- chmod 775 ~/install_sdk.sh
- ~/install_sdk.sh
- echo "sdkman_auto_answer=true" > ~/.sdkman/etc/config
- source "$HOME/.sdkman/bin/sdkman-init.sh"
- sdk install grails $GRAILS_VERSION || true	

branches:
  only:
    - master

script: grails clean && grails test-app --non-interactive --stacktrace